import Link from 'next/link';
import { LEGAL_PLACEHOLDERS } from '@/lib/constants';

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions governing the use of the CloseProof forensic reconciliation interface.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 py-12 px-6">
      <div className="mx-auto max-w-3xl rounded-md border border-slate-200 bg-white p-8">
        <div className="border-b border-slate-200 pb-4 mb-6">
          <Link
            href="/"
            className="text-xs text-blue-800 hover:underline mb-2 inline-block"
          >
            &larr; Back to Close Room
          </Link>
          <h1 className="text-2xl font-bold text-slate-900">Terms of Service</h1>
          <p className="mt-1 text-xs text-slate-500">
            Last updated: October 2026 · Status: Incomplete (Pending Legal Owner Review)
          </p>
        </div>

        {/* Notice of Placeholders */}
        <div className="mb-6 rounded-md border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900">
          <strong className="block mb-1">Notice to Reviewers:</strong>
          This document contains placeholder values for legal entities pending confirmation from the legal lead:
          <ul className="list-disc pl-5 mt-1 font-mono text-[11px]">
            {LEGAL_PLACEHOLDERS.map((p) => (
              <li key={p}>[{p}]</li>
            ))}
          </ul>
        </div>

        <div className="space-y-6 text-sm text-slate-700 leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">1. Scope of Service</h2>
            <p>
              CloseProof provides automated reconciliation analysis, forensic evidence aggregation, and audit packet compilation.
              CloseProof is an investigative analysis and verification assistant.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">2. Core Human-in-the-Loop Principle</h2>
            <p>
              <strong>CloseProof does not post adjustments directly to general ledgers or accounting software without authorized human review.</strong>{' '}
              All reconciliation proposals, candidate matches, journal entry suggestions, and exceptions require explicit review and manual sign-off by a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">3. Disclaimer of Financial Advice</h2>
            <p>
              The outputs generated by automated machine learning models (including Nemotron tiers) and search lookups do not constitute professional accounting, tax, or legal advice.
              Users are solely responsible for verifying the accuracy of all audit schedules before filing or reporting.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">4. Governing Terms</h2>
            <p>
              Service Provider: <code>[{LEGAL_PLACEHOLDERS[0]}]</code><br />
              Registered Address: <code>[{LEGAL_PLACEHOLDERS[1]}]</code><br />
              Jurisdiction: <code>[{LEGAL_PLACEHOLDERS[3]}]</code>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
